- src/pages/index.js
~minder-folden noticed these are wrong
> Add card links

- content/system/runtime/guides/_index.md
- content/system/runtime/guides/conn.md
add conn.c usage guide from https://github.com/urbit/tools/wiki/conn.c-Usage-Guide to runtime guides
> add conn.c guide

- content/courses/urbit-academy/ha.md
Rewrote it to better reflect the course, updated links, dates, etc.
> Updated Hoon Academy page

- content/language/hoon/reference/stdlib/4n.md
https://hackmd.io/@eamsden/HkQIzzIaT
> Incorporate Ed's notes on Nock 12 and +mink

- content/system/kernel/eyre/guides/_index.md
- content/system/kernel/eyre/guides/eauth.md
Add a guide to EAuth.
resolves #62
> eyre: add eauth guide

- content/language/hoon/reference/rune/mic.md
Update micmic to reflect current behaviour and use cases.
resolves #57
> micmic: update explanation

- content/manual/running/vere.md
updates the vere reference for the post-epoch chop/roll system.
resolves #70
> vere manual: update chop & add roll for epochs

- content/language/hoon/reference/stdlib/3d.md
> fix ++shay description, sha-256 not sha-512

- content/courses/app-school/1-arvo.md
- content/courses/app-school/10-scry.md
- content/courses/app-school/11-fail.md
- content/courses/app-school/2-agent.md
- content/courses/app-school/3-imports-and-aliases.md
- content/courses/app-school/4-lifecycle.md
- content/courses/app-school/5-cards.md
- content/courses/app-school/6-pokes.md
- content/courses/app-school/7-sur-and-marks.md
- content/courses/app-school/8-subscriptions.md
- content/courses/app-school/9-vanes.md
minor updates for
hoon 138k
%lick
note:agent:gall
deprecated agents
> app-school: minor updates

- content/courses/hoon-school/B-syntax.md
- content/courses/hoon-school/F-cores.md
- content/courses/hoon-school/G-trees.md
> hoon-school: misc cleanup

- content/language/hoon/reference/stdlib/2j.md
Wasn't sure who to tag, hopefully its clear
> jar: update 'get' docs to reflect what it produces

- content/language/hoon/reference/stdlib/2k.md
Fix incorrect Dojo output in `++get:to`
> get-to-fix-dojo

- content/glossary/_index.md
- content/glossary/axes.md
- content/glossary/axis.md
- content/glossary/clam.md
- content/glossary/cue.md
- content/glossary/head.md
- content/glossary/jam.md
- content/glossary/lark.md
- content/glossary/tail.md
- content/glossary/term.md
add axis, axes, clam, cue, jam, head, tail, lark, term
> add new entries to glossary

- content/language/hoon/examples/_index.md
- content/language/hoon/examples/abc-blocks.md
- content/language/hoon/examples/emirp.md
- content/language/hoon/examples/gleichniszahlenreihe.md
- content/language/hoon/examples/islands.md
- content/language/hoon/examples/luhn-number.md
- content/language/hoon/examples/min-path.md
- content/language/hoon/examples/phone-letters.md
- content/language/hoon/examples/restore-ip.md
- content/language/hoon/examples/rhonda.md
- content/language/hoon/examples/roman.md
- content/language/hoon/examples/solitaire.md
- content/language/hoon/examples/water-towers.md
Also fix order of items in Hoon/Examples
> Add 2 coding competition challenges

- content/courses/app-school/7-sur-and-marks.md
These changes will help others trying to follow along with a fake ship. The agent would not build otherwise.
> App school lesson 7 snippet fixes

- content/courses/_index.md
- content/courses/core-academy/_index.md
- content/courses/core-academy/ca00.md
- content/courses/core-academy/ca01.md
- content/courses/core-academy/ca02.md
- content/courses/core-academy/ca03.md
- content/courses/core-academy/ca04.md
- content/courses/core-academy/ca05.md
- content/courses/core-academy/ca06.md
- content/courses/core-academy/ca07.md
- content/courses/core-academy/ca08.md
- content/courses/core-academy/ca09.md
- content/courses/core-academy/ca10.md
- content/courses/core-academy/ca11.md
- content/courses/core-academy/ca12.md
- content/courses/core-academy/ca13.md
As part of Core Academy 2023, I prepared a series of lesson notes on the kernel and runtime.  These are sometimes thorough and sometimes merely a sketch, but it seems prudent to preserve them in a discoverable format.
> Add Core Academy lesson notes

- content/hoon/reference/stdlib/1c.md
Reverts urbit/docs.urbit.org#208
> Revert "Correct bloq discussion"

- content/hoon/reference/rune/tis.md
redo of https://github.com/urbit/docs.urbit.org/pull/137 due to merge conflicts
> add type nesting note in tis rune ref

- content/hoon/reference/stdlib/1c.md
https://github.com/urbit/docs.urbit.org/pull/215 with merge conflicts resolved
> Revise $bloq discussion

- content/hoon/reference/auras.md
I didn't even know about `@x` until today.
> Add unremarked auras.

- content/build-on-urbit/environment.md
- content/build-on-urbit/hoon-school/B-syntax.md
- content/build-on-urbit/hoon-school/C-azimuth.md
- content/build-on-urbit/hoon-school/D-gates.md
- content/build-on-urbit/hoon-school/E-types.md
- content/build-on-urbit/hoon-school/F-cores.md
- content/build-on-urbit/hoon-school/G-trees.md
- content/build-on-urbit/hoon-school/H-libraries.md
- content/build-on-urbit/hoon-school/I-testing.md
- content/build-on-urbit/hoon-school/J-stdlib-text.md
- content/build-on-urbit/hoon-school/K-doors.md
- content/build-on-urbit/hoon-school/L-struct.md
- content/build-on-urbit/hoon-school/M-typecheck.md
- content/build-on-urbit/hoon-school/N-logic.md
- content/build-on-urbit/hoon-school/O-subject.md
- content/build-on-urbit/hoon-school/P-stdlib-io.md
- content/build-on-urbit/hoon-school/Q-func.md
- content/build-on-urbit/hoon-school/R-metals.md
- content/build-on-urbit/hoon-school/S-math.md
Mostly just cosmetic changes to formatting; a few text changes where material was either in error or unclear.
> Polish Hoon School style, correct errors
